site_name: Centelha da Revolução
repo_name: "2024.1-RPGym-DOC"
repo_url: https://github.com/mdsreq-fga-unb/2024.1-RPGym
theme:
  logo: assets/LogoFaccao.png
  favicon: assets/LogoFaccao.png
  name: material
  language: pt
  features:
    - content.code.annotate
    - content.tabs.link
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - content.code.copy
    - announce.dismiss
    - navigation.footer
    - navigation.indexes
    - search.highlight
    - search.share
    - search.suggest
  palette:
    - scheme: default
      primary: cyan
      accent: orange
      # Mudar para o modo claro
      toggle:
        icon: material/brightness-7 
        name: Mudar para o modo escuro
      # Mudar para o modo escuro
    - scheme: slate
      primary: orange
      accent: cyan
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

site_name: RPGym
nav:
  - Inicio: index.md
  - Facção: faccao/faccao.md
  - Backlogs:
    - Visão Geral: backlogs/backlog-home.md  
    - Backlog do Projeto:
      - Visão Geral do Projeto: backlogs/backlog-do-projeto/visao_do_projeto.md
      - Processo de Desenvolvimento do Software: backlogs/backlog-do-projeto/processos-de-desenvolvimento-de-software.md       
    - Backlog do Produto:
      - Visão Geral do Produto:
          - Visão do Produto: backlogs/backlog-do-produto/visao-do-produto/visao.md
          - Declaração de Posição do Produto: backlogs/backlog-do-produto/visao-do-produto/declaracao-de-posicao-do-produto.md
          - Objetivos do Produto: backlogs/backlog-do-produto/visao-do-produto/objetivos-do-produto.md
          - Elicitação e Descoberta: backlogs/backlog-do-produto/visao-do-produto/elicitacao-e-descoberta.md
          - Tecnologias: backlogs/backlog-do-produto/visao-do-produto/tecnologias.md        
      - Backlog do Produto: backlogs/backlog-do-produto/backlog-do-produto.md
    - Backlog da Sprint:
      - Cronograma: backlogs/backlog-da-sprint/cronograma.md
      - Backlog da Sprint: backlogs/backlog-da-sprint/backlog-da-sprint.md    
  - Missões:
    - Missão 1: missoes/missao1.md
    - Missão 2: missoes/missao2.md
    - Missão 3: missoes/missao3.md
    # - Missão 4: missoes/missao4.md


