site_name: Centelha da Revolução
theme:
  logo: assets/LogoFaccao.png
  favicon: assets/LogoFaccao.png
  name: material
  features:
    - content.code.annotate
    - content.tabs.link
    - header.autohide
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    
extra_css:
  - stylesheets/styles.css

nav:
  - Inicio: index.md
  - Facção: faccao/faccao.md
  - Produto: Produto/visao.md
