site_name: Centelha da Revolução
repo_name: "2024.1-RPGym-DOC"
repo_url: https://github.com/mdsreq-fga-unb/2024.1-RPGym
theme:
  logo: assets/LogoFaccao.png
  favicon: assets/LogoFaccao.png
  name: material
  language: pt
  features:
    - content.code.annotate
    - content.tabs.link
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - content.code.copy
    - announce.dismiss
    - navigation.footer
    - navigation.indexes
    - search.highlight
    - search.share
    - search.suggest
  palette:
    - scheme: default
      primary: cyan
      accent: orange
      # Mudar para o modo claro
      toggle:
        icon: material/brightness-7 
        name: Mudar para o modo escuro
      # Mudar para o modo escuro
    - scheme: slate
      primary: orange
      accent: cyan
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - Inicio: index.md
  - Facção: faccao/faccao.md
  - Visão Geral do Produto:
    - Visão do Produto: Produto/visao.md
    - Declaração de Posição do Produto: Produto/declaracao-de-posicao-do-produto.md
    - Objetivos do Produto: Produto/objetivos-do-produto.md
    - Tecnologias: Produto/tecnologias.md
  - Visão Geral do Projeto:
    - Visão do Projeto: Projeto/visao_do_projeto.md
    - Processo de Desenvolvimento do Software: processos-de-desenvolvimento/processos-de-desenvolvimento-de-software.md
  - Backlog:
    - Backlog: backlog/backlog.md
    - Backlog SAFe: backlog/SAFe.md
    - Backlog do Produto: backlog/backlog-do-produto.md
    - Sprints: backlog/sprints.md
  - Missões:
    - Missão 1: missoes/missao1.md
    - Missão 2: missoes/missao2.md

